homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('interests/', views.interests, name='interests'),
    path('contact/', views.contact, name='contact'),
    path('add-schedule/', views.schedule_add, name='add'),
    path('list-schedule/', views.schedule_list, name='list'),
    path('del/<int:id>', views.schedule_delete, name='del'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Schedule(models.Model):
	nama = models.CharField(max_length=30)
	kategori = models.CharField(max_length=30)
	tempat = models.CharField(max_length=30)
	hari = models.CharField(max_length=9)
	tanggal = models.DateField(auto_now_add=True)
	waktu = models.TimeField(auto_now_add=True)

	def __str__(self):
		return self.nama

homepage/forms.py
from django import forms
from . import models

class Add_Schedule(forms.ModelForm):

	class Meta:
		model = models.Schedule
		fields = ['nama', 'kategori', 'tempat', 'hari',]
    

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .forms import Add_Schedule
from .models import Schedule

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def portfolio(request):
    return render(request, 'portfolio.html')

def interests(request):
    return render(request, 'interests.html')

def contact(request):
    return render(request, 'contact.html')

def schedule_list(request):
	schedules = Schedule.objects.all().order_by('tanggal')
	return render(request, 'list_schedule.html', {'schedules' : schedules})

def schedule_add(request):
	if request.method == 'POST':
		form = Add_Schedule(request.POST)
		if form.is_valid():
			form.save()
			return redirect('homepage:list')
	else:
		form = Add_Schedule()
	return render(request, 'add_schedule.html', {'form' : form})

def schedule_delete(request, id):
	Schedule.objects.get(pk=id).delete()
	return schedule_list(request)

homepage/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="container" style="margin-top:40px; margin-bottom:40px">
            
            <!-- Page Title -->
            <h1>About Me</h1>
            <hr>

            <!-- Bootstrap Grid System -->
            <div class="row">

                <!-- Bootstrap Responsive Column Span-4 -->
                <div class="col-sm-4">
           
                    <!-- Photo Carousel Container -->
                    <div class="container my-3">
                        <h4>Photos of me:</h4>

                        <!-- Bootstrap Carousel JS -->
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">

                            <!-- Indicators -->
                            <ul class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li>
                                <li data-target="#myCarousel" data-slide-to="2"></li>
                            </ul>
  
                            <!-- The Slideshow -->
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img src="{% static 'images/wisuda-1.JPG' %}" class="rounded img-fluid" alt="FotoWisuda1">
                                </div>
                                <div class="carousel-item">
                                    <img src="{% static 'images/wisuda-2.JPG' %}" class="rounded img-fluid" alt="FotoWisuda2">
                                </div>
                                <div class="carousel-item">
                                    <img src="{% static 'images/wisuda-3.JPG' %}" class="rounded img-fluid" alt="FotoWisuda3">
                                </div>
                            </div>
  
                            <!-- Left and right controls -->
                            <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
                                <span class="carousel-control-prev-icon"></span>
                            </a>
                            <a class="carousel-control-next" href="#myCarousel" data-slide="next">
                                <span class="carousel-control-next-icon"></span>
                            </a>

                        </div>
                    </div>

                    <!-- Card Container -->
                    <div class="container" style="margin-top:30px; margin-bottom:30px">

                        <!-- Red About Card -->
                        <div class="card bg-danger text-white">
                            <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                <i class="fas fa-info-circle fa-10x"></i>
                            </div>
                            <div class="card-body text-center">
                                <h2 class="card-title"><strong>ABOUT</strong></h2>
                                <hr>
                                <p class="card-text">A little bit about me.</p>
                                <p class="card-text">Get to know me a little more.</p>
                                <p class="card-text">My little auto-biography.</p>
                                <p class="card-text">And some pictures too.</p>
                                <a href="{% url 'homepage:about' %}" class="btn btn-primary stretched-link">See Profile</a>
                            </div>
                        </div>

                    </div>

                </div>

                <!-- Bootstrap Responsive Column Span-8 -->
                <div class="col-sm-8">
                    <div class="container my-3">

                        <h3>Hello there!</h3>
                        <h2>I'm <strong>PRIMO GIANCARLO UNEPUTTY</strong></h2>
                        <h5>Computer Science Student from University of Indonesia</h5>
                        <hr>

                        <!-- Bootstrap List Group -->
                        <ul class="list-group list-group-flush">

                            <!-- NPM -->
                            <li class="list-group-item list-group-item-dark">
                                <div class="container my-2">
                                    <i class="fas fa-id-card fa-3x fa-pull-left"></i>
                                        <h4><strong>Nomor Pokok Mahasiswa (NPM):</strong></h4>
                                        <h5>1806205180</h5>
                                </div>
                            </li>

                            <!-- Birthday -->
                            <li class="list-group-item list-group-item-secondary">
                                <div class="container my-2">
                                    <i class="fas fa-birthday-cake fa-3x fa-pull-left"></i>
                                        <h4><strong>Birthdate:</strong></h4>
                                        <h5>June 30th 2000</h5>
                                </div>
                            </li>

                            <!-- Age -->
                            <li class="list-group-item list-group-item-dark">
                                <div class="container my-2">
                                    <i class="fas fa-user-circle fa-3x fa-pull-left"></i>
                                        <h4><strong>Age (2019):</strong></h4>
                                        <h5>19 years old and still counting</h5>
                                </div>
                            </li>

                            <!-- Occupation -->
                            <li class="list-group-item list-group-item-secondary">
                                <div class="container my-2">
                                    <i class="fas fa-user-md fa-3x fa-pull-left"></i>
                                        <h4><strong>Occupation:</strong></h4>
                                        <h5>Student at Fasilkom University of Indonesia</h5>
                                </div>
                            </li>

                            <!-- Favorite Food -->
                            <li class="list-group-item list-group-item-dark">
                                <div class="container my-2">
                                    <i class="fas fa-utensils fa-3x fa-pull-left"></i>
                                        <h4><strong>Favorite Food:</strong></h4>
                                        <h5>I like fruits, I guess they're juicy. Especially apples.</h5>
                                </div>
                            </li>

                            <!-- Favorite Beverage -->
                            <li class="list-group-item list-group-item-secondary">
                                <div class="container my-2">
                                    <i class="fas fa-coffee fa-3x fa-pull-left"></i>
                                        <h4><strong>Favorite Beverage:</strong></h4>
                                        <h5>Chocolate milk, either hot or cold.</h5>
                                </div>
                            </li>

                            <!-- Likes -->
                            <li class="list-group-item list-group-item-dark">
                                <div class="container my-2">
                                    <i class="fas fa-thumbs-up fa-3x fa-pull-left"></i>
                                        <h4><strong>What I Like:</strong></h4>
                                        <h5>Preaching about our Lord and Savior, Jesus Christ.</h5>
                                </div>
                            </li>

                            <!-- Dislikes -->
                            <li class="list-group-item list-group-item-secondary">
                                <div class="container my-2">
                                    <i class="fas fa-thumbs-down fa-3x fa-pull-left"></i>
                                        <h4><strong>What I Dislike:</strong></h4>
                                        <h5>Old people driving, women driving, kids driving.</h5>
                                </div>
                            </li>

                            <!-- Hopes & Dreams -->
                            <li class="list-group-item list-group-item-secondary">
                                <div class="container my-2">
                                    <i class="fas fa-comment-dots fa-3x fa-pull-left"></i>
                                        <h4><strong>Hopes and Dreams:</strong></h4>
                                        <h5>Don't have any. Live comfortably, I guess.</h5>
                                </div>
                            </li>

                        </ul>
                        
                    </div>
                </div>

            </div>
        </div>

{% endblock %}

homepage/templates/add_schedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  	<div class="container" style="margin-top:40px; margin-bottom:40px">
  		<h1>Add Your Schedule</h1>

      <!-- Card Container -->
      <div class="container my-3">

        <!-- Yellow Schedule List Card -->
        <div class="card bg-warning text-white">
          <div class="container" style="margin-top:30px; display:flex; justify-content:center">
            <i class="fas fa-file-invoice fa-10x"></i>
          </div>
          <div class="card-body text-center">
            <h2 class="card-text"><strong>LIST</strong></h2>
            <hr>
            <p class="card-text">See all your schedules.</p>
            <p class="card-text">Your own To-Do List.</p>
            <p class="card-text">To remind you of things.</p>
            <p class="card-text">You can delete them too.</p>
            <a href="{% url 'homepage:list' %}" class="btn btn-primary stretched-link">See Schedules</a>
          </div>
        </div>

      </div>   

  		<form class="site-form" action="{% url 'homepage:add' %}" method="POST">
        {% csrf_token %}
  		  {{ form }}
        <input type="submit" value="SUBMIT">
		  </form>	

  	</div>

{% endblock %}

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 	
 	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Personal CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <!-- Font Awesome 5 -->
    <link rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" 
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" 
    crossorigin="anonymous">

    <!-- Website Title  -->
    <title>Primo Giancarlo | PPW Story</title>

  </head>

  <body>

  	<!-- Bootstrap Header Jumbotron -->
  	<div class="jumbotron jumbotron-fluid text-center" style="margin-bottom:0">
  		<h1><strong>Primo Giancarlo Uneputty</strong></h1>
  		<p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p> 
		</div>

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">

  		<!-- Navbar Brand/Logo -->
  		<a class="navbar-brand" href="{% url 'homepage:index' %}"><strong>HOME</strong></a>

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav">

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'homepage:about' %}">About</a>
    			</li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'homepage:portfolio' %}">Portfolio</a>
    			</li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'homepage:interests' %}">Interests</a>
    			</li>
    			
          <li class="nav-item">
      			<a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
    			</li>
            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:list' %}">Schedule</a>
          </li>

  			</ul>
  		</div>

		</nav>

    <div class="wrapper">
      {% block content %}

      {% endblock %}
    </div>

    <!-- Bootstrap Footer Jumbotron -->
    <div class="jumbotron jumbotron-fluid text-center" style="margin-bottom:0">
      <p>This website is incomplete. All Rights reserved. Copyright @ 2019</p>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

homepage/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="container" style="margin-top:40px; margin-bottom:40px">
    
            <!-- Page Title -->
            <h1>Contact Information</h1>
            <hr>

             <!-- Bootstrap Grid System -->
            <div class="row">

                <!-- Bootstrap Responsive Column Span-4 -->
                <div class="col-sm-4">

                    <!-- Card Container -->
                    <div class="container my-3">

                        <!-- Turquoise Contact Card -->
                        <div class="card bg-info text-white">
                            <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                <i class="fas fa-phone-square fa-10x"></i>
                            </div>
                            <div class="card-body text-center">
                                <h2 class="card-text"><strong>CONTACT</strong></h2>
                                <hr>
                                <p class="card-text">How to get in contact.</p>
                                <p class="card-text">My social media profiles.</p>
                                <p class="card-text">Give me a little call maybe.</p>
                                <p class="card-text">I'm antisocial please help.</p>
                                <a href="{% url 'homepage:contact' %}" class="btn btn-primary stretched-link">See Info</a>
                            </div>
                        </div>  

                    </div>
                </div>

                <!-- Bootstrap Responsive Column Span-8 -->
                <div class="col-sm-8">

                    <!-- Card Column Container -->
                    <div class="container my-3">

                        <!-- Bootstrap Card Columns -->
                        <div class="card-columns">

                            <!-- First Contact (Phone) -->
                            <div class="card bg-dark text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fas fa-phone fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Phone Number:</strong></h5>
                                    <p class="card-text">+62-878-7878-9282</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">Call Me</a>
                                </div>
                            </div>

                            <!-- Second Contact (Email) -->
                            <div class="card bg-secondary text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fas fa-envelope fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Email Address:</strong></h5>
                                    <p class="card-text">primo.uneputty@gmail.com</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">Email Me</a>
                                </div>
                            </div>

                            <!-- Third Contact (LINE) -->
                            <div class="card bg-dark text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-line fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Line ID:</strong></h5>
                                    <p class="card-text">primo.giancarlo</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">Add Me</a>
                                </div>
                            </div>

                            <!-- Fourth Contact (Twitter) -->
                            <div class="card bg-secondary text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-twitter fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Twitter Account:</strong></h5>
                                    <p class="card-text">This section is empty.</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">No Twitter</a>
                                </div>
                            </div>  

                            <!-- Fifth Contact (Instagram) -->
                            <div class="card bg-dark text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-instagram fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Instagram Profile:</strong></h5>
                                    <p class="card-text">This section is empty.</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">No Instagram</a>
                                </div>
                            </div>

                            <!-- Sixth Contact (Facebook) -->
                            <div class="card bg-secondary text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-facebook fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Facebook Page:</strong></h5>
                                    <p class="card-text">This section is empty.</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">No Facebook</a>
                                </div>
                            </div>

                            <!-- Seventh Contact (GitHub) -->
                            <div class="card bg-dark text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-gitlab fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>GitLab Repository:</strong></h5>
                                    <p class="card-text">https://gitlab.com/PrimoGU</p>
                                    <a href="https://gitlab.com/PrimoGU" class="btn btn-primary stretched-link">Join Me</a>
                                </div>
                            </div>

                            <!-- Eighth Contact (LinkedIn) -->
                            <div class="card bg-secondary text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-linkedin fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>LinkedIn Page:</strong></h5>
                                    <p class="card-text">This section is empty.</p>
                                    <a href="#" class="btn btn-primary disabled stretched-link">See Me</a>
                                </div>
                            </div>

                            <!-- Ninth Contact (Steam) -->
                            <div class="card bg-dark text-white">
                                <div class="container" style="margin-top:30px; display:flex; justify-content:center">
                                    <i class="fab fa-steam fa-4x"></i>
                                </div>
                                <div class="card-body text-center">
                                    <h5 class="card-text"><strong>Steam Name:</strong></h5>
                                    <p class="card-text">Accerelix</p>
                                    <a href="https://steamcommunity.com/id/acerrelix/" class="btn btn-primary stretched-link">Play With Me</a>
                                </div>
                            </div>
                        
                        </div>

                    </div>
                </div>

            </div>
        </div>

{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

		  <div class="container" style="margin-top:40px; margin-bottom:40px">
    
        <!-- Page Title -->
    		<h1>Home Page</h1>
        <hr>

        <!-- Bootstrap Card Deck -->
   			<div class="card-deck">

          <!-- Red About Card -->
    			<div class="card bg-danger text-white">
    				<div class="container" style="margin-top:30px; display:flex; justify-content:center">
    					<i class="fas fa-info-circle fa-10x"></i>
    				</div>
      				<div class="card-body text-center">
        				<h2 class="card-title"><strong>ABOUT</strong></h2>
                <hr>
        				<p class="card-text">A little bit about me.</p>
        				<p class="card-text">Get to know me a little more.</p>
        				<p class="card-text">My little auto-biography.</p>
        				<p class="card-text">And some pictures too.</p>
        				<a href="{% url 'homepage:about' %}" class="btn btn-primary stretched-link">See Profile</a>
      				</div>
    			</div>

          <!-- Blue Portfolio Card -->
    			<div class="card bg-primary text-white">
    				<div class="container" style="margin-top:30px; display:flex; justify-content:center">
    					<i class="fas fa-file-invoice fa-10x"></i>
    				</div>
      				<div class="card-body text-center">
        				<h2 class="card-text"><strong>PORTFOLIO</strong></h2>
                <hr>
        				<p class="card-text">Just my mini resume.</p>
        				<p class="card-text">All my puny achievements.</p>
        				<p class="card-text">My very lacking experience.</p>
        				<p class="card-text">And my nonexistent skills.</p>
        				<a href="{% url 'homepage:portfolio' %}" class="btn btn-primary stretched-link">See Resume</a>
      				</div>
    			</div>

          <!-- Green Interests Card -->
    			<div class="card bg-success text-white">
    				<div class="container" style="margin-top:30px; display:flex; justify-content:center">
    					<i class="fas fa-gamepad fa-10x"></i>
    				</div>
      				<div class="card-body text-center">
        				<h2 class="card-text"><strong>INTERESTS</strong></h2>
                <hr>
        				<p class="card-text">My hobbies and interests</p>
        				<p class="card-text">What I do in my free time.</p>
        				<p class="card-text">How I alleviate boredom.</p>
        				<p class="card-text">Things you shouldn't do.</p>
        				<a href="{% url 'homepage:interests' %}" class="btn btn-primary stretched-link">See Hobbies</a>
      				</div>
    			</div>

          <!-- Turquoise Contact Card -->
    			<div class="card bg-info text-white">
    				<div class="container" style="margin-top:30px; display:flex; justify-content:center">
    					<i class="fas fa-phone-square fa-10x"></i>
    				</div>
      				<div class="card-body text-center">
        				<h2 class="card-text"><strong>CONTACT</strong></h2>
                <hr>
        				<p class="card-text">How to get in contact.</p>
        				<p class="card-text">My social media profiles.</p>
        				<p class="card-text">Give me a little call maybe.</p>
        				<p class="card-text">I'm antisocial please help.</p>
        				<a href="{% url 'homepage:contact' %}" class="btn btn-primary stretched-link">See Info</a>
      				</div>
    			</div>  

  			</div>

  		</div>

{% endblock %}

homepage/templates/list_schedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  	<div class="container"  style="margin-top:40px; margin-bottom:40px">
  		<h1>View Your Schedules</h1>  

      <!-- Card Container -->
      <div class="container my-3">

        <!-- Blue Add Schedule Card -->
        <div class="card bg-primary text-white">
          <div class="container" style="margin-top:30px; display:flex; justify-content:center">
            <i class="fas fa-calendar-plus fa-10x"></i>
          </div>
          <div class="card-body text-center">
            <h2 class="card-text"><strong>ADD</strong></h2>
            <hr>
            <p class="card-text">Add more schedules.</p>
            <p class="card-text">So you don't forget things.</p>
            <p class="card-text">To help remind you.</p>
            <p class="card-text">Set up your daily targets.</p>
            <a href="{% url 'homepage:add' %}" class="btn btn-primary stretched-link">Add Schedules</a>
          </div>
        </div>

      </div>              

  		<div class="schedules">
        {% for schedule in schedules %}
          <div class="schedule">
            <h2>{{ schedule.nama }}</h2>
            <h3>{{ schedule.kategori }}</h3>
            <p>{{ schedule.tempat }}</p>
            <p>{{ schedule.hari }}</p>
            <p>{{ schedule.tanggal }}</p>
            <p>{{ schedule.waktu }}</p>
            <a href="{% url 'homepage:del' schedule.id %}" class="btn btn-danger" role="button">Delete</a>
          </div>
        {% endfor %}
		  </div>	

  	</div>

{% endblock %}